# Generated by Django 4.2.4 on 2023-09-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopname', models.CharField(max_length=50)),
                ('typeshop', models.CharField(max_length=50)),
                ('empname', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
    ]
